noun1 = input("Enter a noun: ")
adjective = input("Enter an adjective: ")
verb = input("Enter a verb: ")
adverb = input("Enter an adverb: ")
noun2 = input("Enter a noun: ")
adjective2 = input("Enter adjective: ")
plural_noun = input("Enter a plural noun: ")
plural_noun2 = input("Enter a plural noun: ")
body = input("Enter a part of the body: ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
noun6 = input("Enter a noun: ")
body2 = input("Enter a part of the body: ")


print("Ye can always pretend to be a bloodthirsty " + noun1)
print("threatening everyone by waving yer " + adjective)
print("sword in the air, but intil ye learn to " +verb)
print("like a pirate, ye'll never be" + adverb)
print("accepted as an authentic " + noun2)
print("So here's what ye do: Cleverly work into yer daily conversations " + adjective2)
print("pirate phrases such as Ahoy there, " + plural_noun)
print("and Shiver me " + plural_noun2)
print("Remember to drop all yer gs when ye say such words as sailin, spittin, and fightin. This will give ye a/an "+ body)
print("start to being recognized as a swashbucklin " + noun3)
print("Once ye have the lingo down pat, it helps to wear a thre-cornered " + noun4)
print("on yer head, stash a/an " +noun5)
print("in yer pants, and keep a/an " + noun6)
print("perched atop yer " + body2)
print("Aye, now ye be a real pirate!")